name: Publish Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Git SHA
        id: get_sha
        run: echo "::set-output name=SHA_SHORT::$(git rev-parse --short HEAD)"
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            nightwhite634/code-server-node:latest
            nightwhite634/code-server-node:${{ steps.get_sha.outputs.SHA_SHORT }}
          args: --no-cache
