name: Publish Docker image  

on:   # 配置触发workflow的事件
  workflow_dispatch:
  push:
    branches:   # master分支有push时触发此workflow
      - 'main'
jobs:  
  push_to_registry:  
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest 
    steps:  
      - name: Check out the repo
        uses: actions/checkout@v2   
      - name: Log in to Docker Hub
        uses: docker/login-action@v1  
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} 
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2 # docker build & push
        with:
          context: .
          push: true
          tags: nightwhite634/code-server-node:latest
